# Generated by Django 4.2.18 on 2025-02-25 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Type', models.CharField(max_length=10)),
                ('source_id_DR3', models.BigIntegerField(blank=True, null=True)),
                ('gravLensName', models.CharField(blank=True, max_length=30, null=True)),
                ('compId', models.SmallIntegerField(blank=True, null=True)),
                ('Max_separation', models.FloatField(blank=True, null=True)),
                ('Nb_of_published_components', models.SmallIntegerField(blank=True, null=True)),
                ('BibCode', models.CharField(blank=True, max_length=30, null=True)),
                ('RA_center', models.FloatField(blank=True, null=True)),
                ('DEC_center', models.FloatField(blank=True, null=True)),
                ('RA_center_sexa', models.CharField(blank=True, max_length=30, null=True)),
                ('DEC_center_sexa', models.CharField(blank=True, max_length=30, null=True)),
                ('z_source', models.FloatField(blank=True, null=True)),
                ('z_lens', models.FloatField(blank=True, null=True)),
                ('z_bibcode', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LensComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Component', models.CharField(max_length=30)),
                ('RA_best', models.FloatField(blank=True, null=True)),
                ('DEC_best', models.FloatField(blank=True, null=True)),
                ('RA_sexa', models.CharField(blank=True, max_length=30, null=True)),
                ('DEC_sexa', models.CharField(blank=True, max_length=30, null=True)),
                ('DR3', models.CharField(choices=[('TRUE', 'True'), ('FALSE', 'False')], max_length=5)),
                ('FPR', models.CharField(choices=[('TRUE', 'True'), ('FALSE', 'False')], max_length=5)),
                ('RA_pub', models.FloatField(blank=True, null=True)),
                ('DEC_pub', models.FloatField(blank=True, null=True)),
                ('ra_Gaia_DR3', models.FloatField(blank=True, null=True)),
                ('ra_error', models.FloatField(blank=True, null=True)),
                ('dec_Gaia_DR3', models.FloatField(blank=True, null=True)),
                ('dec_error', models.FloatField(blank=True, null=True)),
                ('parallax', models.FloatField(blank=True, null=True)),
                ('parallax_error', models.FloatField(blank=True, null=True)),
                ('parallax_over_error', models.FloatField(blank=True, null=True)),
                ('pm', models.FloatField(blank=True, null=True)),
                ('pmra', models.FloatField(blank=True, null=True)),
                ('pmra_error', models.FloatField(blank=True, null=True)),
                ('pmdec', models.FloatField(blank=True, null=True)),
                ('pmdec_error', models.FloatField(blank=True, null=True)),
                ('astrometric_n_good_obs_al', models.SmallIntegerField(blank=True, null=True)),
                ('astrometric_gof_al', models.FloatField(blank=True, null=True)),
                ('astrometric_chi2_al', models.FloatField(blank=True, null=True)),
                ('astrometric_excess_noise', models.FloatField(blank=True, null=True)),
                ('astrometric_excess_noise_sig', models.FloatField(blank=True, null=True)),
                ('astrometric_params_solved', models.SmallIntegerField(blank=True, null=True)),
                ('pseudocolour', models.FloatField(blank=True, null=True)),
                ('pseudocolour_error', models.FloatField(blank=True, null=True)),
                ('visibility_periods_used', models.SmallIntegerField(blank=True, null=True)),
                ('ruwe', models.FloatField(blank=True, null=True)),
                ('duplicated_source', models.CharField(choices=[('TRUE', 'True'), ('FALSE', 'False')], max_length=5)),
                ('phot_g_mean_flux', models.FloatField(blank=True, null=True)),
                ('phot_g_mean_flux_error', models.FloatField(blank=True, null=True)),
                ('phot_g_mean_mag', models.FloatField(blank=True, null=True)),
                ('phot_bp_mean_flux', models.FloatField(blank=True, null=True)),
                ('phot_bp_mean_flux_error', models.FloatField(blank=True, null=True)),
                ('phot_bp_mean_mag', models.FloatField(blank=True, null=True)),
                ('phot_rp_mean_flux', models.FloatField(blank=True, null=True)),
                ('phot_rp_mean_mag', models.FloatField(blank=True, null=True)),
                ('bp_rp', models.FloatField(blank=True, null=True)),
                ('phot_g_mean_mag_error', models.FloatField(blank=True, null=True)),
                ('phot_bp_mean_mag_error', models.FloatField(blank=True, null=True)),
                ('phot_rp_mean_mag_error', models.FloatField(blank=True, null=True)),
                ('nObsComp', models.SmallIntegerField(blank=True, null=True)),
                ('ra_FPR', models.FloatField(blank=True, null=True)),
                ('stdra_FPR', models.FloatField(blank=True, null=True)),
                ('dec_FPR', models.FloatField(blank=True, null=True)),
                ('stddec_FPR', models.FloatField(blank=True, null=True)),
                ('G_FPR', models.FloatField(blank=True, null=True)),
                ('stdG_FPR', models.FloatField(blank=True, null=True)),
                ('z_milli', models.FloatField(blank=True, null=True)),
                ('flag_z_milli', models.CharField(blank=True, max_length=30, null=True)),
                ('ref_z_milli', models.CharField(blank=True, max_length=30, null=True)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.lens')),
            ],
        ),
    ]
