# Generated by Django 5.0.4 on 2024-09-04 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Gravitational lens of a quasar', max_length=30, unique=True)),
                ('RA_mean', models.DecimalField(decimal_places=8, max_digits=11)),
                ('DEC_mean', models.DecimalField(decimal_places=8, max_digits=10)),
                ('Author', models.CharField(help_text='Year and author of published paper', max_length=20)),
                ('BibCode', models.CharField(help_text='Year and author of published paper', max_length=20)),
                ('GraL', models.CharField(choices=[('TRUE', 'True'), ('FALSE', 'False')], max_length=5)),
                ('Max_separation', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LensComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Component', models.CharField(max_length=5)),
                ('RA_best', models.DecimalField(decimal_places=8, max_digits=11)),
                ('DEC_best', models.DecimalField(decimal_places=8, max_digits=10)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.lens')),
            ],
        ),
    ]
