# Generated by Django 5.0.4 on 2024-09-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lens',
            name='Author',
            field=models.CharField(blank=True, help_text='Year and author of published paper', max_length=20),
        ),
        migrations.AlterField(
            model_name='lens',
            name='BibCode',
            field=models.CharField(blank=True, help_text='Year and author of published paper', max_length=20),
        ),
        migrations.AlterField(
            model_name='lens',
            name='DEC_mean',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lens',
            name='GraL',
            field=models.CharField(blank=True, choices=[('TRUE', 'True'), ('FALSE', 'False')], max_length=5),
        ),
        migrations.AlterField(
            model_name='lens',
            name='RA_mean',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='lenscomponent',
            name='DEC_best',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lenscomponent',
            name='RA_best',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
    ]
