# Generated by Django 4.2.18 on 2025-02-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lens',
            name='DEC_center',
            field=models.FloatField(blank=True, help_text='DEC center [°]', null=True),
        ),
        migrations.AlterField(
            model_name='lens',
            name='DEC_center_sexa',
            field=models.CharField(blank=True, help_text='DEC center [hh:mm:ss]', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lens',
            name='RA_center',
            field=models.FloatField(blank=True, help_text='RA center [°]', null=True),
        ),
        migrations.AlterField(
            model_name='lens',
            name='RA_center_sexa',
            field=models.CharField(blank=True, help_text='RA center [hh:mm:ss]', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lens',
            name='z_bibcode',
            field=models.CharField(blank=True, help_text='z bibcode', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lens',
            name='z_lens',
            field=models.FloatField(blank=True, help_text='z lens', null=True),
        ),
        migrations.AlterField(
            model_name='lens',
            name='z_source',
            field=models.FloatField(blank=True, help_text='z source', null=True),
        ),
        migrations.AlterField(
            model_name='lenscomponent',
            name='DEC_best',
            field=models.FloatField(blank=True, help_text='DEC best [°]', null=True),
        ),
        migrations.AlterField(
            model_name='lenscomponent',
            name='DEC_sexa',
            field=models.CharField(blank=True, help_text='DEC best [hh:mm:ss]', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lenscomponent',
            name='RA_best',
            field=models.FloatField(blank=True, help_text='RA best [°]', null=True),
        ),
        migrations.AlterField(
            model_name='lenscomponent',
            name='RA_sexa',
            field=models.CharField(blank=True, help_text='RA best [hh:mm:ss]', max_length=30, null=True),
        ),
    ]
