# Generated by Django 5.0.4 on 2024-09-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_lens_author_alter_lens_bibcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lens',
            name='Type',
            field=models.CharField(default='', help_text='Type of the lens (Double, Quad, Unknown)', max_length=10),
        ),
        migrations.AlterField(
            model_name='lens',
            name='BibCode',
            field=models.CharField(blank=True, help_text='BibCode of published paper', max_length=20),
        ),
    ]
