# Generated by Django 4.2.18 on 2025-02-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_lens_dec_center_alter_lens_dec_center_sexa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lens',
            name='DEC_center_sexa',
            field=models.CharField(blank=True, help_text='DEC center [d:mm:ss.ss]', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lens',
            name='RA_center_sexa',
            field=models.CharField(blank=True, help_text='RA center [d:mm:ss.ss]', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lenscomponent',
            name='DEC_sexa',
            field=models.CharField(blank=True, help_text='DEC best [d:mm:ss.ss]', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lenscomponent',
            name='RA_sexa',
            field=models.CharField(blank=True, help_text='RA best [d:mm:ss.ss]', max_length=30, null=True),
        ),
    ]
