# Generated by Django 5.2.4 on 2025-07-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_lens_dec_center_sexa_alter_lens_ra_center_sexa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lens',
            name='Max_separation',
            field=models.FloatField(blank=True, help_text='Max separation ["]', null=True),
        ),
    ]
