# Generated by Django 5.0.4 on 2024-09-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_lens_type_alter_lens_bibcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lens',
            name='Type',
            field=models.CharField(help_text='Type of the lens (Double, Quad, Unknown)', max_length=10),
        ),
    ]
