# Generated by Django 5.2.4 on 2025-07-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_lens_max_separation'),
    ]

    operations = [
        migrations.AddField(
            model_name='lens',
            name='BibCode_TD',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='lens',
            name='ErrtAB',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lens',
            name='ErrtAC',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lens',
            name='ErrtAD',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lens',
            name='ErrtBC',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lens',
            name='ErrtBD',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lens',
            name='ErrtCD',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lens',
            name='tAB',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lens',
            name='tAC',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lens',
            name='tAD',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lens',
            name='tBC',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lens',
            name='tBD',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lens',
            name='tCD',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
