# Generated by Django 5.2.4 on 2025-07-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_lens_bibcode_td_lens_errtab_lens_errtac_lens_errtad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lens',
            name='tAB',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
