# Generated by Django 5.2.4 on 2025-07-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_lens_nb_of_published_components'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lens',
            name='compId',
        ),
        migrations.RemoveField(
            model_name='lens',
            name='source_id_DR3',
        ),
        migrations.RemoveField(
            model_name='lens',
            name='z_lens',
        ),
        migrations.RemoveField(
            model_name='lenscomponent',
            name='DR3',
        ),
        migrations.RemoveField(
            model_name='lenscomponent',
            name='FPR',
        ),
        migrations.AddField(
            model_name='lenscomponent',
            name='compId',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lenscomponent',
            name='source_id_DR3',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lenscomponent',
            name='z_deflector',
            field=models.FloatField(blank=True, help_text='z lens', null=True),
        ),
    ]
