# Generated by Django 5.2.4 on 2025-07-24 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_lens_compid_remove_lens_source_id_dr3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lenscomponent',
            old_name='astrometric_params_solved',
            new_name='astrometric_params',
        ),
        migrations.RenameField(
            model_name='lenscomponent',
            old_name='dec_Gaia_DR3',
            new_name='dec_DR3',
        ),
        migrations.RenameField(
            model_name='lenscomponent',
            old_name='ra_Gaia_DR3',
            new_name='ra_DR3',
        ),
    ]
