# Generated by Django 5.2.4 on 2025-07-24 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_remove_lenscomponent_duplicated_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lenscomponent',
            name='phot_bp_mean_mag_error',
        ),
        migrations.RemoveField(
            model_name='lenscomponent',
            name='phot_g_mean_mag_error',
        ),
        migrations.RemoveField(
            model_name='lenscomponent',
            name='phot_rp_mean_mag_error',
        ),
    ]
