# Generated by Django 5.2.4 on 2025-07-24 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_lens_z_deflector_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lenscomponent',
            old_name='DEC_sexa',
            new_name='dec_sexa',
        ),
        migrations.RenameField(
            model_name='lenscomponent',
            old_name='RA_sexa',
            new_name='ra_sexa',
        ),
    ]
