# Generated by Django 5.2.4 on 2025-07-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_rename_dec_sexa_lenscomponent_dec_sexa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lens',
            name='ErrtAB',
            field=models.FloatField(blank=True, help_text='Err_tAB [d]', null=True),
        ),
        migrations.AlterField(
            model_name='lens',
            name='ErrtAC',
            field=models.FloatField(blank=True, help_text='Err_tAC [d]', null=True),
        ),
        migrations.AlterField(
            model_name='lens',
            name='ErrtAD',
            field=models.FloatField(blank=True, help_text='Err_tAD [d]', null=True),
        ),
        migrations.AlterField(
            model_name='lens',
            name='ErrtBC',
            field=models.FloatField(blank=True, help_text='Err_BC [d]', null=True),
        ),
        migrations.AlterField(
            model_name='lens',
            name='ErrtBD',
            field=models.FloatField(blank=True, help_text='Err_tBD [d]', null=True),
        ),
        migrations.AlterField(
            model_name='lens',
            name='ErrtCD',
            field=models.FloatField(blank=True, help_text='Err_tCD [d]', null=True),
        ),
        migrations.AlterField(
            model_name='lens',
            name='tAB',
            field=models.CharField(blank=True, help_text='tAB [d]', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lens',
            name='tAC',
            field=models.FloatField(blank=True, help_text='tAC [d]', null=True),
        ),
        migrations.AlterField(
            model_name='lens',
            name='tAD',
            field=models.FloatField(blank=True, help_text='tAD [d]', null=True),
        ),
        migrations.AlterField(
            model_name='lens',
            name='tBC',
            field=models.FloatField(blank=True, help_text='tBC [d]', null=True),
        ),
        migrations.AlterField(
            model_name='lens',
            name='tBD',
            field=models.FloatField(blank=True, help_text='tBD [d]', null=True),
        ),
        migrations.AlterField(
            model_name='lens',
            name='tCD',
            field=models.FloatField(blank=True, help_text='tCD [d]', null=True),
        ),
    ]
