# Generated by Django 5.2.4 on 2025-07-30 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_lens_errtab_alter_lens_errtac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lens',
            name='DEC_center_sexa',
            field=models.CharField(blank=True, help_text='DEC center [deg:min:sec]', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lens',
            name='RA_center_sexa',
            field=models.CharField(blank=True, help_text='RA center [hr:min:sec]', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lenscomponent',
            name='dec_sexa',
            field=models.CharField(blank=True, help_text='DEC best [deg:min:sec]', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lenscomponent',
            name='ra_sexa',
            field=models.CharField(blank=True, help_text='RA best [hr:min:sec]', max_length=30, null=True),
        ),
    ]
